### ISSUE TITLE
Multi-process isn't working

### ISSUE THREAD

**Issue by theskymaybe** [UKPLab/EasyNMT#17]
Hello guys, and thank you for your awesome library!
I'm currently struggling with making test_multi_process_translation.py script working. When it comes to the multi-process part, the following error occures:

`2021-03-04 19:00:46 | INFO | easynmt.EasyNMT | Start multi-process pool on devices: cuda:0
Traceback (most recent call last):
  File "test_multi_process_translation.py", line 80, in <module>
    process_pool = model.start_multi_process_pool()
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/site-packages/easynmt/EasyNMT.py", line 258, in start_multi_process_pool
    p.start()
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/data/home/k.kirillova/anaconda/envs/fairseq/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BaseFairseqModel.make_generation_fast_.<locals>.train'`

Could you please give me any ideas on how to fix this? Thanks in advance!

**Comment by YaroslavKozyrev** [comment]
Same for me...

**Comment by nreimers** [comment]
Will have a look. So far it appears to work the the opus-mt model, but the fairseq models throw this exception. Not sure why.

As soon as Transformers 4.4.0 is released, this project will get finally rid of the dependency of fairseq and will use transformers only. Then, the mbart50 and m2m model will also work in multi process.

**Comment by theskymaybe** [comment]
Thanks a lot!

**Comment by R4ZZ3** [comment]
I got it working on Windows 10 in Docker and was able to convert the thing to work with 418m model.
I then tried to convert the model to work in AWS Lambda with Container support and got to the point that AWS lambda doesn't support multiprocessing. Without going to the depths and try myself to change the fairseq model loading implementation do you @nreimers  know whether there is easy option to load model without multiprocessing (Either now or once transformers 4.4.0 will be ready)?

**Comment by nreimers** [comment]
@R4ZZ3 
Does the traditional translate() method work for you?

The test_multi_process_translation.py  script makes only sense if you want to translate using multiple GPUs.

**Comment by R4ZZ3** [comment]
No,
It breaks down in the model loading step. I am trying to use the regular translate with some changes (works locally):
{
  "errorMessage": "[Errno 38] Function not implemented",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
    "  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
    "  File \"<frozen importlib._bootstrap>\", line 702, in _load\n",
    "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/task/app.py\", line 30, in <module>\n    model = EasyNMT('m2m_100_418M', cache_folder='/model')\n",
    "  File \"/var/lang/lib/python3.8/site-packages/easynmt/EasyNMT.py\", line 86, in __init__\n    module_class = import_from_string(self.config['model_class'])\n",
    "  File \"/var/lang/lib/python3.8/site-packages/easynmt/util.py\", line 56, in import_from_string\n    module = importlib.import_module(module_path)\n",
    "  File \"/var/lang/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/lang/lib/python3.8/site-packages/easynmt/models/Fairseq.py\", line 12, in <module>\n    from fairseq import checkpoint_utils, distributed_utils, tasks, utils\n",
    "  File \"/var/lang/lib/python3.8/site-packages/fairseq/__init__.py\", line 24, in <module>\n    import fairseq.pdb  # noqa\n",
    "  File \"/var/lang/lib/python3.8/site-packages/fairseq/pdb.py\", line 16, in <module>\n    _stdin_lock = multiprocessing.Lock()\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/context.py\", line 68, in Lock\n    return Lock(ctx=self.get_context())\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/synchronize.py\", line 162, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/synchronize.py\", line 57, in __init__\n    sl = self._semlock = _multiprocessing.SemLock(\n"
  ]
}

**Comment by PanicButtonPressed** [comment]
> @R4ZZ3
> Does the traditional translate() method work for you?
> 
> The test_multi_process_translation.py script makes only sense if you want to translate using multiple GPUs.

Could you explain, why it just makes sense to run the script using multiple GPUs? Is there no way to speed up the translation process by using multiple cpu cores?

**Comment by nreimers** [comment]
@PanicButtonPressed 
The transformer  model uses out-of-the-box already multiple cores. So it does not make a difference if you use 1 process that encodes on two cores (and e.g. can translate 100 sentences / minute) or two processes which fight for the compute power (and might only encode 40 sentences / minute each).

But for GPUs only 1 GPU is used per process. If you have 2 GPUs, each process can use an individual GPU.

**Comment by R4ZZ3** [comment]
Some background why the multiprocessing doesn't work:
https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/

**Comment by rom1504** [comment]
Tested all models, it works for me
