### ISSUE TITLE
Missing supported translate pair with M2M_100 model

### ISSUE THREAD

**Issue by nguyenhuuthuat09** [UKPLab/EasyNMT#25]
Hi, I found that M2M_100 support translate directly between any pair in 100 languages (9900 pairs). But when I use EasyNMT with M2M_100 model, it doesn't support all of these pairs.

Example: EasyNMT can't translate directly from 'th' (Thai) to 'en' (English) while M2M_100 model does support this pair. 

And when I tried to use [HuggingFace](https://huggingface.co/facebook/m2m100_418M) to translate directly between Thai and English, it work perfectly.

Can you please solve the problem? By the way, thank you for creating EasyNMT.

**Comment by nreimers** [comment]
Hi @nguyenhuuthuat09 
Thanks for pointing this out. Will fix it

I think in these cases you just get a warning and translation will still be done?

Best
Nils

**Comment by nguyenhuuthuat09** [comment]
Hi, when I tried, the translation can't be done.

```
from easynmt import EasyNMT

model = EasyNMT('m2m_100_418M')
model.translate('นายเกา เผยอีกว่า ขณะนี้รัฐบาลกลางกำลังพิจารณาว่าจีนควรใช้วัคซีนที่แตกต่างออกไป ที่ผลิตจากเทคโนโลยีใหม่เพื่อสร้างภูมิคุ้มกันต่อโรคโควิด-19', target_lang='en')
```

The error is "ValueError: Translation for the language combination th-en not supported".

![image](https://user-images.githubusercontent.com/29718711/115393293-b6ca8e00-a20b-11eb-8750-45de7b6dd177.png)

**Comment by AgrimPrasad** [comment]
Thank you for creating EasyNMT. It's very easy to get started. However, such unsupported language pairs are a major showstopped for this library in my opinion.

For example, German (`de`) to Hindi (`hi`) throws unsupported error too. Since the default model `opus-mt` also doesn't support these languages, it makes some languages untranslate-able with this library.


This is with the model `m2m_100_1.2B`:

```
ValueError: Translation for the language combination de-hi not supported
```

Traceback:

```
INFO:     61.93.181.247:0 - "GET /?target_lang=hi&text=Hallo%20Welt&source_lang=de HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.7/asyncio/futures.py", line 263, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
    future.result()
  File "/usr/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<ipython-input-4-960ee109d093>", line 17, in translate_get
    return model.translate(text, target_lang=target_lang, source_lang=source_lang)
  File "/usr/local/lib/python3.7/dist-packages/easynmt/EasyNMT.py", line 176, in translate
    translated_sentences = self.translate_sentences(splitted_sentences, target_lang=target_lang, source_lang=source_lang, show_progress_bar=show_progress_bar, beam_size=beam_size, batch_size=batch_size, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/easynmt/EasyNMT.py", line 273, in translate_sentences
    output.extend(self.translator.translate_sentences(sentences_sorted[start_idx:start_idx+batch_size], source_lang=source_lang, target_lang=target_lang, beam_size=beam_size, device=self.device, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/easynmt/models/Fairseq.py", line 86, in translate_sentences
    raise ValueError("Translation for the language combination {}-{} not supported".format(source_lang, target_lang))
ValueError: Translation for the language combination de-hi not supported
```

**Comment by AgrimPrasad** [comment]
I suppose the issue is that not all the possible permutations of supported languages have been added to the language list here? https://github.com/UKPLab/EasyNMT/blob/46cf8e458f4068aca212b855543509ad88360685/models/m2m_100_418M/config.yaml#L344

**Comment by nreimers** [comment]
The bug should now be fixed.

You might need to re-download the model. For this, go to your ~/.cache/torch/easynmt folder and remove the respective folder for the m2m models.

Let me know if there are other issues.

**Comment by nguyenhuuthuat09** [comment]
Hi @nreimers, I has just checked your newest update, and I think there are some redundant pairs. 

Example: `"af-azbt"`, `"ar-bnbt"`,... Because `"azbt"`, `"bnbt"`,... are not in supported language of M2M_100 model. Base on [this paper](https://arxiv.org/pdf/2010.11125.pdf) and [huggingface model page](https://huggingface.co/facebook/m2m100_418M).

I found that in EasyNMT, M2M_100 model support 127 languages instead of 100. And your newest update has 16,002 (127\*126) pair instead of 9900 (100\*99) pairs.

The same things same happen to MBart50_m2m, too.

**Comment by nreimers** [comment]
These are the language codes as provided by facebook in the fairseq repository. The mentioned lang codes are specific character encodings of these languages. 

Soon Version 2 will be released which will remove  fairseq and will only use huggingface

**Comment by nguyenhuuthuat09** [comment]
I'm glad to hear this. Thank you so much. Looking forward to seeing your new version soon.

**Comment by nguyenhuuthuat09** [comment]
Hi @nreimers, can you please update release version with pip install?

**Comment by nguyenhuuthuat09** [comment]
@nreimers, I find out why, EasyNMT will download easynmt.json from server: http://easynmt.net/models/m2m_100_418m/easynmt.json

Can you please update it?

**Comment by nreimers** [comment]
File is updated

**Comment by nguyenhuuthuat09** [comment]
@nreimers, thank you so much. Everything seems to be working perfectly.
