### ISSUE TITLE
Docker image easynmt/api:2.0-cpu crashes when trying to run on mac

### ISSUE THREAD

**Issue by AgrimPrasad** [UKPLab/EasyNMT#26]
Running this on a 2017 Macbook. Docker image `easynmt/api:2.0-cpu` fails to start with exceptions, while `easynmt/api:1.1-cpu` was running fine with the same `docker run` command previously.

```
docker run -p 24081:80 -v /Users/agrim/Downloads/easynmt-models:/cache easynmt/api:2.0-cpu

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/easynmt/EasyNMT.py", line 92, in __init__
    self.translator = module_class(easynmt_path=model_path, **self.config['model_args'])
KeyError: 'model_args'
Checking for script in /app/prestart.sh
There is no script /app/prestart.sh
[2021-04-27 14:38:22 +0000] [13] [INFO] Starting gunicorn 20.1.0
[2021-04-27 14:38:22 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2021-04-27 14:38:22 +0000] [12] [INFO] Listening at: http://0.0.0.0:8080 (12)
[2021-04-27 14:38:22 +0000] [13] [INFO] Listening at: http://0.0.0.0:80 (13)
[2021-04-27 14:38:22 +0000] [13] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-04-27 14:38:22 +0000] [12] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-04-27 14:38:22 +0000] [17] [INFO] Booting worker with pid: 17
[2021-04-27 14:38:22 +0000] [18] [INFO] Booting worker with pid: 18
[2021-04-27 14:38:22 +0000] [19] [INFO] Booting worker with pid: 19
[2021-04-27 14:38:24 +0000] [19] [INFO] Started server process [19]
[2021-04-27 14:38:24 +0000] [17] [INFO] Started server process [17]
[2021-04-27 14:38:24 +0000] [17] [INFO] Waiting for application startup.
[2021-04-27 14:38:24 +0000] [19] [INFO] Waiting for application startup.
[2021-04-27 14:38:24 +0000] [17] [INFO] Application startup complete.
[2021-04-27 14:38:24 +0000] [19] [INFO] Application startup complete.
{"loglevel": "info", "workers": "1", "bind": "0.0.0.0:8080", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "host": "0.0.0.0", "port": "8080"}
Booted as backend: True
Load model: opus-mt
[2021-04-27 14:38:25 +0000] [18] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 36, in <module>
    model = EasyNMT(model_name, load_translator=IS_BACKEND, **model_args)
  File "/usr/local/lib/python3.8/site-packages/easynmt/EasyNMT.py", line 92, in __init__
    self.translator = module_class(easynmt_path=model_path, **self.config['model_args'])
KeyError: 'model_args'
[2021-04-27 14:38:25 +0000] [18] [INFO] Worker exiting (pid: 18)
[2021-04-27 14:38:25 +0000] [12] [INFO] Shutting down: Master
[2021-04-27 14:38:25 +0000] [12] [INFO] Reason: Worker failed to boot.
{"loglevel": "info", "workers": "1", "bind": "0.0.0.0:8080", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "host": "0.0.0.0", "port": "8080"}
One of the processes has already exited.
```

**Comment by nreimers** [comment]
Hi @AgrimPrasad 
Thanks for reporting.

In v2, the config files for models have slightly be changed.

It appears, that your docker container tries to load a model with the old config file format. 

Run your docker command like this and it should work:
```
docker run -p 24081:80 -v /Users/agrim/Downloads/easynmt-models-v2:/cache easynmt/api:2.0-cpu
```

**Comment by AgrimPrasad** [comment]
Thanks, changing the mount directory works, although this does mean that the models need to be downloaded again in this case.

**Comment by nreimers** [comment]
When you use the OPUS-MT model, you can also download the most recent json from here:
http://easynmt.net/models/v2/opus-mt/easynmt.json

And store (replace) it in the easynmt/opus-mt folder. Then the old model files can be kept.

With the mBART and m2m models, downloading them is sadly necessary as they have changed from using fairseq to using huggingface transformers
