### ISSUE TITLE
Sending large documents for translation with GET endpoint can sometimes result in URL parser error

### ISSUE THREAD

**Issue by AgrimPrasad** [UKPLab/EasyNMT#36]
With large documents (several thousand characters), I see a crash in the URL parser. Tried with different source and target languages. Also, for the same source text, the translation may sometimes succeed, but then fail again. For example, for the sample request URL given below, the URL parser may sometimes succeed and sometimes fail with exception.

I'm using the last 1.x commit of EasyNMT (specifically commit `61fcf7154f01f56c02be6d30b1c5d0921b91aa2e`) as it has better benchmarks than 2.x for fairseq models, but I believe the same issue should be there for the latest version too as I don't think the URL parser would have changed. I'm using the `m2m_100_418M` model with a T4 GPU if that matters at all.

EasyNMT error logs:

```
[2021-05-25 14:58:29 +0000] [16] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
  File "httptools/parser/parser.pyx", line 245, in httptools.parser.parser.cb_on_url
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 216, in on_url
    parsed_url = httptools.parse_url(url)
  File "httptools/parser/parser.pyx", line 468, in httptools.parser.parser.parse_url
httptools.parser.errors.HttpParserInvalidURLError: invalid url b'ividual+level+we+need+to+take+up+responsibility+to+curb+the+spread+of+this+virus%2C%22+said+Dr+Rao%0D%0A%0D%0APromotedListen+to+the+latest+songs%2C+only+on+JioSaavn.com%0D%0A%0D%0AWhen+it+comes+to+Bengaluru%2C+Dr+Rao+said+the+lockdown+had+reduced+the+number+of+emergency+oxygen+requirements+and+the+panic.+%22That+is+because+the+virus+has+stopped+moving+because+we+have+stopped+moving%2C%22+he+said.+%22Generally%2C+as+a+rule%2C+a+health+care+system+will+not+be+able+to+cope+with+a+sudden+rise+in+numbers%2C+emergency+oxygen+requirements+or+health+care.+The+other+big+concern+is+trained+manpower.%22%0D%0A%0D%0AComments%0D%0AMucormycosis%2C+commonly+known+as+Black+Fungus%2C+is+also+on+the+rise+in+the+state.+Dr+Rao+said%3A+%22At+HCG+we+are+treating+30+cases+and+the+number+is+on+the+rise.+In+Karnataka%2C+currently%2C+it+must+be+about+700+cases.+It+looks+like+an+epidemic+within+a+pandemic+at+this+juncture.+We+need+to+understand+the+source+of+this+infection%2C+have+early+detection+and+treatment.+A+committee+will+give+a+clear+strategy+for+the+state.+We+don%27t+need+to+scare+people+about+black+fungus%2C+we+need+to+create+awareness.+What+we+have+seen+in+the+patients+-+they+have+all+been+Covid+positive%2C+most+have+been+given+steroids%2C+majority+had+high+sugar.+30+to+40+per+cent+had+been+given+oxygen+and+most+important+-+none+of+them+had+been+vaccinated.%22%0D%0A%0D%0A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 167, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserCallbackError: the on_url callback failed
[2021-05-25 14:58:29 +0000] [18] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
  File "httptools/parser/parser.pyx", line 245, in httptools.parser.parser.cb_on_url
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 216, in on_url
    parsed_url = httptools.parse_url(url)
  File "httptools/parser/parser.pyx", line 468, in httptools.parser.parser.parse_url
httptools.parser.errors.HttpParserInvalidURLError: invalid url b'irus+is+now+being+reported+more+from+rural+Karnataka+with+often+a+weak+health+infrastructure.%0D%0A%0D%0ADr+Vishal+Rao+of+the+HCG+hospitals+and+a+member+of+the+Karnataka+Covid+task+force+said%2C+%22It+is+going+to+be+an+uphill+task+as+we+move+towards+the+districts+as+the+health+care+systems+get+overburdened+there.+Even+the+oxygen+management.+In+cities%2C+we+have+the+privilege+that+oxygen+comes+to+the+doorstep+of+the+hospital.+Whereas+in+villages+and+districts%2C+hospitals+have+to+carry+their+cylinders+to+refill+them.+Public+health+experts+and+virologists+are+repeatedly+trying+to+enhance+the+surveillance+in+villages+to+ensure+we+are+better+prepared+in+villages.+This+is+the+time+to+ramp+up+the+preparation+for+villages.%22%0D%0A%0D%0AHe+also+said+that+the+lockdown+%22definitely+had+a+very+significant+impact%22+on+the+daily+infections.+%22From+50%2C000+cases+everyday%2C+today+we+are+at+around+20%2C000+odd+cases.It+is+not+a+reassurance+that+once+the+lockdown+is+lifted%2C+we+will+continue+to+have+these+low+numbers.+But+what+is+of+concern+is+that+the+positivity+rate+still+sticks+at+around+20+per+cent+and+the+mortality+has+jumped+to+about+2+per+cent.+We+need+to+understand+that+when+the+waves+flatten%2C+it+is+not+that+the+virus+is+taking+rest.+It+is+a+socio-economic+virus+and+the+more+we+improve+interactions+without+safety%2C+we+are+going+to+explode+and+expand+the+spread+of+this+virus.+At+an+ind'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 167, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserCallbackError: the on_url callback failed
```

Full request URL path + query params:

```
/translate?beam_size=2&source_lang=en&target_lang=de&text=Bengaluru%3A+Karnataka+-+one+of+the+worst+hit+states+in+the+country+in+the+second+wave+of+COVID-19%2C+has+been+witnessing+a+slump+in+the+new+case+numbers+over+the+last+few+weeks.+The+authorities%2C+however%2C+are+of+the+view+that+It+is+far+too+early+to+relax.%0D%0AThe+number+of+COVID-19+outnumbered+fresh+infections+in+Karnataka+yet+again+on+Tuesday%2C+as+the+state+reported+38%2C224+discharges+and+22%2C758+new+cases.+Of+the+new+cases+reported+today%2C+6%2C243+were+from+Bengaluru.%0D%0A%0D%0A%22If+you+look+at+the+numbers%2C+it+has+been+reducing+very+drastically.+Except+for+a+few+districts+where+the+numbers+are+not+coming+down.+In+most+of+the+districts+and+Bengaluru%2C+the+numbers+have+come+down.+The+number+should+come+down+drastically+so+that+we+can+unlock+from+the+lockdown%2C%22+Deputy+Chief+Minister+Dr+Ashwath+Narayan+told+NDTV.%0D%0A%0D%0AThe+state+is+in+the+middle+of+a+strict+shutdown.+But+that+doesn%27t+mean+any+major+reduction+in+the+demand+for+oxygen+in+Bengaluru+as+ICU+beds+still+remain+full.%0D%0A%0D%0A%22Since+the+number+has+come+down+very+drastically+-+now+it+is+5%2C000+odd+cases+in+Bengaluru+%28daily+infections%29+-+from+when+it+had+almost+reached+25%2C000%2C+it+is+a+great+relief.+When+it+comes+to+ICU+or+ventilator%2C+however%2C+there+is+still+a+lot+of+demand%2C%22+he+said.%0D%0A%0D%0AAn+extra+concern+is+that+the+virus+is+now+being+reported+more+from+rural+Karnataka+with+often+a+weak+health+infrastructure.%0D%0A%0D%0ADr+Vishal+Rao+of+the+HCG+hospitals+and+a+member+of+the+Karnataka+Covid+task+force+said%2C+%22It+is+going+to+be+an+uphill+task+as+we+move+towards+the+districts+as+the+health+care+systems+get+overburdened+there.+Even+the+oxygen+management.+In+cities%2C+we+have+the+privilege+that+oxygen+comes+to+the+doorstep+of+the+hospital.+Whereas+in+villages+and+districts%2C+hospitals+have+to+carry+their+cylinders+to+refill+them.+Public+health+experts+and+virologists+are+repeatedly+trying+to+enhance+the+surveillance+in+villages+to+ensure+we+are+better+prepared+in+villages.+This+is+the+time+to+ramp+up+the+preparation+for+villages.%22%0D%0A%0D%0AHe+also+said+that+the+lockdown+%22definitely+had+a+very+significant+impact%22+on+the+daily+infections.+%22From+50%2C000+cases+everyday%2C+today+we+are+at+around+20%2C000+odd+cases.It+is+not+a+reassurance+that+once+the+lockdown+is+lifted%2C+we+will+continue+to+have+these+low+numbers.+But+what+is+of+concern+is+that+the+positivity+rate+still+sticks+at+around+20+per+cent+and+the+mortality+has+jumped+to+about+2+per+cent.+We+need+to+understand+that+when+the+waves+flatten%2C+it+is+not+that+the+virus+is+taking+rest.+It+is+a+socio-economic+virus+and+the+more+we+improve+interactions+without+safety%2C+we+are+going+to+explode+and+expand+the+spread+of+this+virus.+At+an+individual+level+we+need+to+take+up+responsibility+to+curb+the+spread+of+this+virus%2C%22+said+Dr+Rao%0D%0A%0D%0APromotedListen+to+the+latest+songs%2C+only+on+JioSaavn.com%0D%0A%0D%0AWhen+it+comes+to+Bengaluru%2C+Dr+Rao+said+the+lockdown+had+reduced+the+number+of+emergency+oxygen+requirements+and+the+panic.+%22That+is+because+the+virus+has+stopped+moving+because+we+have+stopped+moving%2C%22+he+said.+%22Generally%2C+as+a+rule%2C+a+health+care+system+will+not+be+able+to+cope+with+a+sudden+rise+in+numbers%2C+emergency+oxygen+requirements+or+health+care.+The+other+big+concern+is+trained+manpower.%22%0D%0A%0D%0AComments%0D%0AMucormycosis%2C+commonly+known+as+Black+Fungus%2C+is+also+on+the+rise+in+the+state.+Dr+Rao+said%3A+%22At+HCG+we+are+treating+30+cases+and+the+number+is+on+the+rise.+In+Karnataka%2C+currently%2C+it+must+be+about+700+cases.+It+looks+like+an+epidemic+within+a+pandemic+at+this+juncture.+We+need+to+understand+the+source+of+this+infection%2C+have+early+detection+and+treatment.+A+committee+will+give+a+clear+strategy+for+the+state.+We+don%27t+need+to+scare+people+about+black+fungus%2C+we+need+to+create+awareness.+What+we+have+seen+in+the+patients+-+they+have+all+been+Covid+positive%2C+most+have+been+given+steroids%2C+majority+had+high+sugar.+30+to+40+per+cent+had+been+given+oxygen+and+most+important+-+none+of+them+had+been+vaccinated.%22%0D%0A%0D%0ADelhi+received+144.8+mm+rainfall+in+May+this+year%2C+the+highest+for+the+month+in+13+years%2C+according+to+the+India+Meteorological+Department+%28IMD%29.%0D%0A%22No+rain+is+predicted+in+the+next+four+to+five+days.+So%2C+this+is+the+highest+rainfall+in+May+since+2008%2C%22+Kuldeep+Srivastava%2C+the+head+of+the+IMD%27s+regional+forecasting+centre%2C+said+today.%0D%0A%0D%0AThe+Safdarjung+Observatory%2C+considered+the+official+marker+for+the+city%2C+had+recorded+21.1+mm+rainfall+last+year%2C+26.9+mm+in+2019+and+24.2+mm+in+2018.%0D%0A%0D%0AIt+had+gauged+40.5+mm+precipitation+in+2017%3B+24.3+mm+in+2016%3B+3.1+mm+in+2015+and+100.2+mm+in+2014%2C+according+to+IMD+data.%0D%0A%0D%0A
```

**Comment by AgrimPrasad** [comment]
Should I use the POST endpoint instead to avoid this? If yes, could someone suggest the expected POST request body please? I don't see much in the swagger documentation for the POST request body. Thanks!

<img width="1464" alt="Screenshot 2021-05-25 at 11 21 01 PM" src="https://user-images.githubusercontent.com/6386887/119524098-e858eb00-bdaf-11eb-8a36-0aeb56616aa1.png">

**Comment by AgrimPrasad** [comment]
Seems it works fine with with POST requests having the following JSON request body. So I guess this is not a very high priority issue:

```json
{
  "target_lang": "hi",
  "source_lang": "en",
  "text": [
    "Bengaluru: Karnataka - one of the worst hit states in the country in the second wave of COVID-19, has been witnessing a slump in the new case numbers over the last few weeks. The authorities, however, are of the view that It is far too early to relax.\r\nThe number of COVID-19 outnumbered fresh infections in Karnataka yet again on Tuesday, as the state reported 38,224 discharges and 22,758 new cases. Of the new cases reported today, 6,243 were from Bengaluru.\r\n\r\n\"If you look at the numbers, it has been reducing very drastically. Except for a few districts where the numbers are not coming down. In most of the districts and Bengaluru, the numbers have come down. The number should come down drastically so that we can unlock from the lockdown,\" Deputy Chief Minister Dr Ashwath Narayan told NDTV.\r\n\r\nThe state is in the middle of a strict shutdown. But that doesn't mean any major reduction in the demand for oxygen in Bengaluru as ICU beds still remain full.\r\n\r\n\"Since the number has come down very drastically - now it is 5,000 odd cases in Bengaluru (daily infections) - from when it had almost reached 25,000, it is a great relief. When it comes to ICU or ventilator, however, there is still a lot of demand,\" he said.\r\n\r\nAn extra concern is that the virus is now being reported more from rural Karnataka with often a weak health infrastructure.\r\n\r\nDr Vishal Rao of the HCG hospitals and a member of the Karnataka Covid task force said, \"It is going to be an uphill task as we move towards the districts as the health care systems get overburdened there. Even the oxygen management. In cities, we have the privilege that oxygen comes to the doorstep of the hospital. Whereas in villages and districts, hospitals have to carry their cylinders to refill them. Public health experts and virologists are repeatedly trying to enhance the surveillance in villages to ensure we are better prepared in villages. This is the time to ramp up the preparation for villages.\"\r\n\r\nHe also said that the lockdown \"definitely had a very significant impact\" on the daily infections. \"From 50,000 cases everyday, today we are at around 20,000 odd cases.It is not a reassurance that once the lockdown is lifted, we will continue to have these low numbers. But what is of concern is that the positivity rate still sticks at around 20 per cent and the mortality has jumped to about 2 per cent. We need to understand that when the waves flatten, it is not that the virus is taking rest. It is a socio-economic virus and the more we improve interactions without safety, we are going to explode and expand the spread of this virus. At an individual level we need to take up responsibility to curb the spread of this virus,\" said Dr Rao\r\n\r\nPromotedListen to the latest songs, only on JioSaavn.com\r\n\r\nWhen it comes to Bengaluru, Dr Rao said the lockdown had reduced the number of emergency oxygen requirements and the panic. \"That is because the virus has stopped moving because we have stopped moving,\" he said. \"Generally, as a rule, a health care system will not be able to cope with a sudden rise in numbers, emergency oxygen requirements or health care. The other big concern is trained manpower.\"\r\n\r\nComments\r\nMucormycosis, commonly known as Black Fungus, is also on the rise in the state. Dr Rao said: \"At HCG we are treating 30 cases and the number is on the rise. In Karnataka, currently, it must be about 700 cases. It looks like an epidemic within a pandemic at this juncture. We need to understand the source of this infection, have early detection and treatment. A committee will give a clear strategy for the state. We don't need to scare people about black fungus, we need to create awareness. What we have seen in the patients - they have all been Covid positive, most have been given steroids, majority had high sugar. 30 to 40 per cent had been given oxygen and most important - none of them had been vaccinated.\"\r\n\r\nDelhi received 144.8 mm rainfall in May this year, the highest for the month in 13 years, according to the India Meteorological Department (IMD).\r\n\"No rain is predicted in the next four to five days. So, this is the highest rainfall in May since 2008,\" Kuldeep Srivastava, the head of the IMD's regional forecasting centre, said today.\r\n\r\nThe Safdarjung Observatory, considered the official marker for the city, had recorded 21.1 mm rainfall last year, 26.9 mm in 2019 and 24.2 mm in 2018.\r\n\r\nIt had gauged 40.5 mm precipitation in 2017; 24.3 mm in 2016; 3.1 mm in 2015 and 100.2 mm in 2014, according to IMD data.\r\n\r\n"
  ]
}

```

**Comment by nreimers** [comment]
Hi @AgrimPrasad 
URLs (when you use the GET method) are limited in length. After a certain length, strange things can happen.

So for longer docs, it is always advisable to send them via POST.

Will add a note to the documentation.
