### ISSUE TITLE
OSError: Can't load tokenizer for 'Helsinki-NLP/opus-mt-en-yo'.

### ISSUE THREAD

**Issue by ajesujoba** [UKPLab/EasyNMT#5]
I want to translate from English to Yoruba, but I am getting the above OS error 

```
Exception: Can't load tokenizer for 'Helsinki-NLP/opus-mt-en-yo'. Make sure that:

- 'Helsinki-NLP/opus-mt-en-yo' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'Helsinki-NLP/opus-mt-en-yo' is the correct path to a directory containing relevant tokenizer files


Traceback (most recent call last):
  File "translatefile.py", line 19, in <module>
    translations = model.translate(sentences,  target_lang='yo')
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/EasyNMT.py", line 122, in translate
    translated_sentences = self.translate_sentences(splitted_sentences, target_lang=target_lang, source_lang=source_lang, show_progress_bar=show_progress_bar, beam_size=beam_size, batch_size=batch_size, **kwargs)
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/EasyNMT.py", line 208, in translate_sentences
    raise e
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/EasyNMT.py", line 203, in translate_sentences
    translated = self.translate_sentences(grouped_sentences, source_lang=lng, target_lang=target_lang, show_progress_bar=show_progress_bar, beam_size=beam_size, batch_size=batch_size, **kwargs)
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/EasyNMT.py", line 220, in translate_sentences
    output.extend(self.translator.translate_sentences(sentences_sorted[start_idx:start_idx+batch_size], source_lang=source_lang, target_lang=target_lang, beam_size=beam_size, device=self.device, **kwargs))
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/models/OpusMT.py", line 46, in translate_sentences
    tokenizer, model = self.load_model(model_name)
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/easynmt/models/OpusMT.py", line 28, in load_model
    tokenizer = MarianTokenizer.from_pretrained(model_name)
  File "/home/alabi/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1760, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'Helsinki-NLP/opus-mt-en-yo'. Make sure that:

- 'Helsinki-NLP/opus-mt-en-yo' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'Helsinki-NLP/opus-mt-en-yo' is the correct path to a directory containing relevant tokenizer files

```

Translating from Yoruba to English worked well. What am I doing wrong?

**Comment by nreimers** [comment]
This message indicates that there is sadly no model available for that direction for opus-mt.

You could check if your language is supported by the m2m_100 model
