### ISSUE TITLE
MBart50Converter requires the protobuf library but it was not found in your environment.

### ISSUE THREAD

**Issue by TheMY3** [UKPLab/EasyNMT#69]
Try to use docker image with model `mbart50_m2m`
Command: `docker run --env EASYNMT_MODEL=mbart50_m2m --env TIMEOUT=600 --env MAX_WORKERS_FRONTEND=1 -p 24080:80 easynmt/api:2.0-cpu`
And Its exited with trace:
```
[2022-05-26 12:48:19 +0000] [36] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 36, in <module>
    model = EasyNMT(model_name, load_translator=IS_BACKEND, **model_args)
  File "/usr/local/lib/python3.8/site-packages/easynmt/EasyNMT.py", line 92, in __init__
    self.translator = module_class(easynmt_path=model_path, **self.config['model_args'])
  File "/usr/local/lib/python3.8/site-packages/easynmt/models/AutoModel.py", line 32, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name, **self.tokenizer_args)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 407, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1709, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1781, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/mbart/tokenization_mbart50_fast.py", line 128, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 99, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/usr/local/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py", line 708, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/usr/local/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py", line 301, in __init__
    requires_protobuf(self)
  File "/usr/local/lib/python3.8/site-packages/transformers/file_utils.py", line 574, in requires_protobuf
    raise ImportError(PROTOBUF_IMPORT_ERROR.format(name))
ImportError: 
MBart50Converter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment.
```
Does anybody works on docker images and can fix it?

**Comment by TheMY3** [comment]
For a local development I pull repository and install all dependencies to docker image, if you want - I can make it as PR.
